databases:
  - name: openeats-db
    plan: free

services:
  - type: web
    name: openeats
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://openeats.onrender.com,https://openeats-web.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: openeats-db
          property: connectionString
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SEED_ADMIN_EMAIL
        value: "admin@semed.local"
      - key: SEED_ADMIN_PASSWORD
        value: "Admin123!"
